[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    #Features a probar:
    playlist: modulo playlist
    player: modulo player
    tracks: modulo tracks

    #Clasificicacion de pruebas:
    smoke: fundamental para validar el funcionamiento básico
    regression: cuando se realizan cambios
    functional: pruebas funcionales
    functional_positive: Si verifica un caso esperado - positive
    functional_negative: Si verifica un error o un caso inesperado - negative
    performance: Marca para rendimiento
    security: Marca para pruebas relacionadas con seguridad
    structure_validation: Marca para validación de esquemas
    equivalence_partition: Marca para pruebas de partición de equivalencias
    special_cases: Marca para casos especiales o edge cases

#loggers configuracion
log_cli = 1
log_level = DEBUG
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S